// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)



/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
 
  nodeSidebar: [{ type: 'autogenerated', dirName: 'node' }],
  docusaurusSidebar: [{ type: 'autogenerated', dirName: 'docusaurus' }],
  otherSidebar: [{ type: 'autogenerated', dirName: '其他' }],
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'JavaScript教程',
      items: [
        'javascript/intro',
        'javascript/syntax',
        'javascript/dom',
        'javascript/module',
      ],
    },
  ],

};

module.exports = sidebars;